Repository ludviglundgren/qbittorrent-cli, pull requests merged in 2023-05, with the labels that each got.

#40 Filter qbt list command by torrent state.
  cmd/add.go
  cmd/compare.go
  cmd/edit.go
  cmd/hash.go
  cmd/list.go
  cmd/move.go
  cmd/pause.go
  cmd/remove.go
  cmd/resume.go
  internal/domain/config.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/domain.go
  pkg/qbittorrent/methods.go
Labels: enhancement

#50 feat(import): improve log message for dry-run
  cmd/import.go
Labels: enhancement

#51 feat(move): implement exclude-tags
  cmd/move.go
Labels: enhancement

#52 feat(reannounce): implement reannounce
  README.md
  cmd/qbt/main.go
Labels: enhancement

#53 fix(reannounce): add missing reannounce handler
  cmd/reannounce.go
Labels: bug, enhancement

#54 chore(deps): update packages
  go.mod
  go.sum
Labels: enhancement

#55 fix(importer): tests
  .github/workflows/test.yml
  cmd/export.go
  cmd/export_test.go
  internal/importer/rtorrent_test.go
  pkg/qbittorrent/fastresume.go
  test/import/sessions/.gitkeep
Labels: enhancement

#58 fix: set cookieurl
  internal/config/config.go
  pkg/qbittorrent/methods.go
Labels: enhancement

#57 feat(remove): add option to remove paused
  cmd/remove.go
  pkg/qbittorrent/methods.go
Labels: enhancement

#61 fix: code cleanup
  cmd/add.go
  cmd/edit.go
  cmd/export.go
  cmd/import.go
  cmd/reannounce.go
Labels: enhancement

#64 refactor: qbit methods
  cmd/add.go
  cmd/export.go
  cmd/list.go
  cmd/move.go
  cmd/reannounce.go
  cmd/remove.go
  pkg/qbittorrent/client.go
  pkg/qbittorrent/domain.go
  pkg/qbittorrent/methods.go
Labels: enhancement

#65 fix(list): hashes colliding short flag
  cmd/list.go
Labels: bug
