Repository ludviglundgren/qbittorrent-cli, pull requests merged in 2024-08, with the labels that each got.

#97 feat(ci): update workflows
  .github/workflows/release.yml
  .goreleaser.yml
  go.mod
  go.sum
Labels: build

#96 docs: add table of contents
  README.md
Labels: documentation

#91 chore(deps): update x/* and protobuf
  go.mod
  go.sum
Labels: build

#88 fix(config): add Windows home dir path
  internal/config/config.go
Labels: config, os:windows

#93 feat: add recheck command
  README.md
  cmd/torrent.go
  cmd/torrent_recheck.go
Labels: enhancement

#98 feat: validate hashes
  .gitignore
  cmd/torrent_category.go
  cmd/torrent_list.go
  cmd/torrent_pause.go
  cmd/torrent_recheck.go
  cmd/torrent_remove.go
  cmd/torrent_resume.go
  cmd/torrent_tracker.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: enhancement

#99 fix(torrent): improve glob detection
  cmd/torrent_add.go
Labels: enhancement
