Repository ludviglundgren/qbittorrent-cli, pull requests merged in 2025-05, with the labels that each got.

#119 fix(torrent_add): add 'stopped' option
  cmd/torrent_add.go
Labels: bug

#115 fix(importer): typos, logging and dry run handling
  README.md
  cmd/torrent_import.go
  internal/importer/deluge.go
Labels: enhancement

#113 feat: add torrents from http(s) links
  README.md
  cmd/torrent_add.go
Labels: enhancement

#121 feat(torrent-add): implement stop condition
  cmd/torrent_add.go
Labels: enhancement

#122 chore(deps): upgrade Go to v1.24
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: build

#127 feat(cli): silence usage with -q and --quiet
  cmd/app.go
  cmd/bencode.go
  cmd/category.go
  cmd/qbt/main.go
  cmd/tag.go
  cmd/torrent_add.go
  cmd/torrent_category.go
  cmd/torrent_compare.go
  cmd/torrent_export.go
  cmd/torrent_hash.go
  cmd/torrent_import.go
  cmd/torrent_list.go
  cmd/torrent_pause.go
  cmd/torrent_reannounce.go
  cmd/torrent_recheck.go
  cmd/torrent_remove.go
  cmd/torrent_resume.go
  cmd/torrent_tag.go
  cmd/torrent_tracker.go
  cmd/update.go
  cmd/version.go
  internal/config/config.go
Labels: enhancement

#128 feat: add --recheck to torrent add with --paused
  cmd/torrent_add.go
Labels: enhancement
